### ISSUE TITLE
Compatibility with Calypso Light and Calypso Basic

### ISSUE THREAD

**Issue by AnnnSt** [eclipse/keyple-java-example#20]
Hi @jeanpierrefortune 
Good day to you !
Since the current use case examples are targeting for Calypso Prime, I would like to check with you whether the current Keyple terminal Java library is compatible with Calypso Light and Calypso Basic product? Do i need to modify the library or just the use cases?
Thanks a lot in advance 

BR 
Ann

**Comment by jeanpierrefortune** [comment]
Hi @AnnnSt 
I'm sorry for the long delay in answering.
Concerning the support of Calypso Light and Calypso Basic cards, there are no changes to do in the Keyple library, these types of cards are already supported.
However, some operations will not be available for these cards (Stored Value for example).
If you think of a particular point, do not hesitate to come back to us.
Best regards,
Jean-Pierre

**Comment by AnnnSt** [comment]
Hi Jean-Pierre, 

Noted with thanks for your response.

BR
Ann
